---
  - hosts: tag_group_customer_hosts
    remote_user: ubuntu
    become: yes
    vars_files:
      - vars/global.yml
    pre_tasks:
     - name: 'update apt cache'
       raw: 'sudo apt-get -y update'
     - name: 'install python'
       raw: 'sudo apt-get -y install python'
    gather_facts: no
    roles:
      - update_servers

