---
- set_fact: 
    node: "{{ item }}"

- block:

  - ec2_eni:
      private_ip_address: "{{ node.private_ip_address }}"
      description: "{{ node.name }} network port"
      subnet_id: "{{ public_subnet_id }}"
      security_groups: "{{ node.security_group }}"
      region: "{{ region }}"
      state: present
    register: managment_interface

  - debug:
      msg: "{{ managment_interface }}"

  - ec2:
      instance_type: "{{ node.instance_type}}"
      image: "{{ node.image }}"
      wait: true 
      region: "{{ region }}"
      keypair: "{{ node.keypair }}"
      network_interface: "{{ managment_interface.interface.id }}"
      exact_count: 1
      count_tag: 
        Name: "{{ node.name }}"
      instance_tags:
        group: customer_hosts
        Name: "{{ node.name }}"
    register: instance_details

  - set_fact:
      public_ip_address: instance_details.public_ip_address
    when: instance_details.public_ip_address is defined

  - name: Add the EC2 instance to the local host group
    local_action: lineinfile 
                  dest="./hosts" 
                  regexp="{{ public_ip_address }}"
                  insertafter="[{{ node.tag_group }}]" 
                  line="{{ public_ip_address }}"
    when: public_ip_address is defined


  - name: Wait for SSH to come up
    local_action: wait_for 
                  host={{ public_ip_address }} 
                  port=22 
                  state=started
    when: public_ip_address is defined

  environment:
    AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
    AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
    AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
