---
- set_fact: 
    node: "{{ item }}"

- set_fact: 
    elastic_ips: []

- set_fact: 
    interface_ids: []

- block:

  - include: attach_network_interfaces.yml
    with_items: "{{ node.network_interfaces }}"

  - ec2:
      instance_type: "{{ node.instance_type}}"
      image: "{{ node.image }}"
      wait: true 
      region: "{{ region }}"
      keypair: "{{ node.keypair }}"
      network_interfaces: "{{ interface_ids }}"
      exact_count: 1
      count_tag: 
        Name: "{{ node.name }}"
      instance_tags:
        group: customer_hosts
        Name: "{{ node.name }}"
    register: instance_details

  - debug:
      msg: "{{ elastic_ips }}"

  - debug:
      msg: "{{ instance_details }}"

  - set_fact:
      instance_id: "{{ instance_details.tagged_instances[0].id }}"

  - debug:
      msg: "{{ instance_id }}"

  - ec2_remote_facts:
      region: "{{ region }}"
      filters:
        instance-id: "{{ instance_id }}"
    register: instance_details

  - set_fact:
      public_ip_address: instance_details.public_ip_address
    when: instance_details.instances[0].public_ip_address is defined

  - name: Add the EC2 instance to the local host group
    local_action: lineinfile 
                  dest="./hosts" 
                  regexp="{{ public_ip_address }}"
                  insertafter="[{{ node.tag_group }}]" 
                  line="{{ public_ip_address }}"
    when: public_ip_address is defined


#  - name: Wait for SSH to come up
#    local_action: wait_for 
#                  host={{ public_ip_address }} 
#                  port=22 
#                  state=started
#    when: public_ip_address is defined

  environment:
    AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
    AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
    AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
