---
- set_fact: 
    node: "{{ item }}"

- set_fact: 
    interface_ids: []

- set_fact: 
    interface_description: "Wibbly wobbly interface"

- include: attach_network_interfaces.yml
  with_items: "{{ node.network_interfaces }}"

- ec2:
    instance_type: "{{ node.instance_type}}"
    image: "{{ node.image }}"
    wait: true 
    region: "{{ region }}"
    keypair: "{{ node.keypair }}"
    network_interfaces: "{{ interface_ids }}"
    user_data: "{{ lookup('template', 'basic_config.j2') }}"     
    exact_count: 1
    count_tag: 
      Name: "{{ node.name }}"
    instance_tags:
      group: "{{ node.tag_group }}"
      Name: "{{ node.name }}"
  register: instance_details
