---
region: eu-west-1

nodes:
  - name: Ubuntu1
    instance_type: t2.micro
    security_group: ansible
    image: ami-f90a4880
    keypair: ansible
    tag_group: customer_hosts
    private_ip_address: 10.0.0.100
  - name: Ubuntu2
    instance_type: t2.micro
    security_group: ansible
    image: ami-f90a4880
    keypair: ansible
    tag_group: customer_hosts
    private_ip_address: 10.0.0.101
  - name: vMX1
    instance_type: m4.xlarge
    security_group: ansible
    image: ami-5ea0f027
    tag_group: routers
    keypair: ansible
    private_ip_address: 10.0.0.102
