- debug:
    msg: "{{ node }} info: {{ item }}"

- name: make route permenant
  lineinfile:
    path: /etc/network/interfaces.d/eth1.cfg
    regexp: '^up route add -net "{{ item.destination }}"'
    line: up route add -net "{{ item.destination }}" gw "{{ item.next_hop }}"
  when: item.next_hop is defined
