---
- name: Install Apache
  apt:
    name: apache2
    state: present
- service:
    name: apache2
    state: started
    enabled: yes
- name: turning on eth1
  copy:
    src: ../files/eth1.cfg
    dest: /etc/network/interfaces.d/eth1.cfg
    owner: root
    group: root
    mode: 0644
- service:
    name: networking
    state: restarted
- name: lookup node variables from array
  set_fact: 
    node: "{{ nodes.servers|selectattr('name', 'equalto', ec2_tag_Name) | list }}"
- name: display routes
  debug:
    msg: "{{ node[0].routes }}"

- include: add_routes.yml
  with_items: "{{ node[0].routes }}"

