---
- block:
  - set_fact:
      subnet: "{{ item }}"
  
  - name: Create Subnet
    ec2_vpc_subnet:
      state:            "present"
      vpc_id:           "{{ vpc_id }}"
      map_public:       true
      cidr:             "{{ subnet.cidr }}"
      az:               "{{ region }}a"
      region:           "{{ region }}"
      resource_tags:
        Name:           "{{ subnet.name }}"
    register: created_subnet
  
  - set_fact:
      subnet_ids: "{{ subnet_ids}} + [ '{{ created_subnet.subnet.id }}' ] "

  environment:
    AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
    AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
    AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
