---
- block:
  - set_fact:
      subnet: "{{ item }}"
  
  - name: Create Subnet
    ec2_vpc_subnet:
      state:            "present"
      vpc_id:           "{{ vpc_id }}"
      map_public:       true
      cidr:             "{{ subnet.cidr }}"
      az:               "{{ region }}a"
      region:           "{{ region }}"
      resource_tags:
        Name:           "{{ subnet.name }}"
    register: created_subnet
  
  - name: Set Public Subnet ID in variable
    set_fact:
      created_subnet_id: "{{ created_subnet.subnet.id }}"
  
  - name: Create Internet Gateway
    ec2_vpc_igw:
      vpc_id:           "{{ vpc_id }}"
      region:           "{{ region }}"
      state:            "present"
    register: vpc_igw
  
  - name: Set Internet Gateway ID in variable
    set_fact:
      igw_id:           "{{ vpc_igw.gateway_id }}"
  
  - name: Set up subnet route table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      tags:
        Name: "Public"
      subnets:
        - "{{ created_subnet_id }}"
      routes:
        - dest: "0.0.0.0/0"
          gateway_id: "{{ igw_id }}"

  environment:
    AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
    AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
    AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
