---
- block:
  - name: Create VPC
    ec2_vpc_net:
      name:             "{{ vpc_name }}"
      cidr_block:       "{{ vpc_cidr_block }}"
      region:           "{{ region }}"
      state:            "present"
    register: vpc

  - name: Set VPC ID in variable
    set_fact:
      vpc_id:           "{{ vpc.vpc.id }}"
  
  - include: create_subnet.yml
    with_items: "{{ subnets }}"

  - name: Create a security group
    local_action: 
      module: ec2_group
      name: "{{ security_group_name }}"
      description: Auto deployed security group
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: basic_firewall
  
  environment:
    AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
    AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
    AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
